# .github/workflows/js-lint.yml
name: JS Syntax Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  js-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run basic JS syntax check
        run: |
          find . -name "*.js" -print0 | xargs -0 -n1 node --check
